apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2500)"]
        #command: ["bash", "-c", "exit 1" ]
      restartPolicy: Never
  backoffLimit: 1
