apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        #image: perl
        image: docker.intuit.com/oicp/standard/external/mysql:20.01.08
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(12000)"]
        #command: ["bash", "-c", "exit 1" ]
      restartPolicy: Never
  backoffLimit: 1
