apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: hello
      value: 1
    - name: bye
      value: 2
    - name: what
      value: 3
  templates:
  - name: whalesay
    container:
      image: roffe/kubectl
      command: ["/usr/local/bin/bash"]
      args: ["-c", "kubectl delete pods `kubectl get pods| awk '{print $1}'`" ]
